version: '3.1'

services:

  app:
    build: ./docker
    ports: 
      - 3000:3000

  app_2:
    build: ./docker
    ports: 
      - 3001:3000

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080